-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS escola.professores
(
    prof_nome character varying(40) NOT NULL,
    prof_cpf numeric(11, 0) NOT NULL,
    prof_data_nasc date NOT NULL,
    prof_telefone numeric(12, 0) NOT NULL,
    prof_email character varying(30),
    PRIMARY KEY (prof_cpf)
);

CREATE TABLE IF NOT EXISTS escola.disciplinas
(
    disc_codigo serial NOT NULL,
    disc_nome character varying(50) NOT NULL,
    carga_horaria numeric(3, 0) NOT NULL,
    prof_cpf_fk numeric(11, 0) NOT NULL,
    PRIMARY KEY (disc_codigo)
);

CREATE TABLE IF NOT EXISTS escola.alunos
(
    alu_nome character varying(40) NOT NULL,
    alu_cpf numeric(11, 0) NOT NULL,
    alu_data_nasc date NOT NULL,
    alu_telefone numeric(12, 0) NOT NULL,
    alu_email character varying(30),
    PRIMARY KEY (alu_cpf)
);

CREATE TABLE IF NOT EXISTS escola.matriculas
(
    alu_cpf_fk numeric(11, 0) NOT NULL,
    disc_codigo_fk serial NOT NULL,
    data_matri date NOT NULL,
    status_matri character varying(9) NOT NULL,
    nota_final numeric(3, 1) NOT NULL,
    num_faltas numeric(3, 0) NOT NULL
);

ALTER TABLE IF EXISTS escola.disciplinas
    ADD CONSTRAINT prof_cpf_fk FOREIGN KEY (prof_cpf_fk)
    REFERENCES escola.professores (prof_cpf) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS escola.matriculas
    ADD CONSTRAINT alu_cpf_fk FOREIGN KEY (alu_cpf_fk)
    REFERENCES escola.alunos (alu_cpf) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS escola.matriculas
    ADD CONSTRAINT disc_codigo_fk FOREIGN KEY (disc_codigo_fk)
    REFERENCES escola.disciplinas (disc_codigo) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;