-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS loja_roupas.clientes
(
    cli_cpf numeric(11, 0) NOT NULL,
    cli_nome character varying(40) NOT NULL,
    PRIMARY KEY (cli_cpf)
);

CREATE TABLE IF NOT EXISTS loja_roupas.pedidos
(
    ped_id serial NOT NULL,
    qtd numeric(2, 0) NOT NULL,
    cli_cpf_fk numeric(11, 0) NOT NULL,
    prod_id_fk serial NOT NULL,
    PRIMARY KEY (ped_id)
);

CREATE TABLE IF NOT EXISTS loja_roupas.produtos
(
    prod_id serial NOT NULL,
    prod_nome character varying(30) NOT NULL,
    tamanho_cm numeric(3, 0) NOT NULL,
    cor character varying(20) NOT NULL,
    for_cnpj_fk character varying(14) NOT NULL,
    PRIMARY KEY (prod_id)
);

CREATE TABLE IF NOT EXISTS loja_roupas.fornecedores
(
    for_cnpj character varying(14) NOT NULL,
    for_nome character varying(40) NOT NULL,
    PRIMARY KEY (for_cnpj)
);

ALTER TABLE IF EXISTS loja_roupas.pedidos
    ADD FOREIGN KEY (cli_cpf_fk)
    REFERENCES loja_roupas.clientes (cli_cpf) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS loja_roupas.pedidos
    ADD FOREIGN KEY (prod_id_fk)
    REFERENCES loja_roupas.produtos (prod_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS loja_roupas.produtos
    ADD FOREIGN KEY (for_cnpj_fk)
    REFERENCES loja_roupas.fornecedores (for_cnpj) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;